name: ydown
description: ""

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  youtube_explode_dart: ^3.1.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  device_info_plus: ^11.0.0
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
